# Generated by Django 2.2.4 on 2019-08-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='starterdeck',
            name='deck_image',
            field=models.FileField(upload_to=''),
        ),
    ]
