# Generated by Django 2.2.4 on 2019-08-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190806_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
