# Generated by Django 2.2.4 on 2019-08-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190807_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
